-- Nothing to seed for local development anymore — schools, groups, and
-- students are all self-service (join codes created through the app's UI),
-- which is the whole point of the pivot in migration 0002. Sign up through
-- the app as a driver/parent/school to test the flow end to end; see README.
